### ISSUE TITLE
Viewport or ? too wide

### ISSUE THREAD

**Issue by membranepotential** [membranepotential/ascstudymonitor#24]
Shows unnecessary horizontal scrollbar

**Comment by trueter** [comment]
Thank you for reporting @membranepotential. Can you share a screenshot and which browser you are using? Thanks again! :)

**Comment by membranepotential** [comment]
![image](https://user-images.githubusercontent.com/14043981/84089159-94ae8f80-a9ee-11ea-8799-c032e7f2cd16.png)

Happens on vivaldi and firefox

**Comment by membranepotential** [comment]
Thanks for looking into it... But sorry, still an issue ;-) I will try myself later on, now I know where to look :)

**Comment by trueter** [comment]
Wtfff

**Comment by trueter** [comment]
Chrome
![image](https://user-images.githubusercontent.com/1976714/84141697-e3424500-aa53-11ea-831b-ee7e56f33fc0.png)

Firefox
![image](https://user-images.githubusercontent.com/1976714/84141844-15ec3d80-aa54-11ea-87da-94d5954a073f.png)

Vivaldi
![image](https://user-images.githubusercontent.com/1976714/84141882-26041d00-aa54-11ea-8eb3-018f120a5353.png)

Safari
![image](https://user-images.githubusercontent.com/1976714/84141929-3b794700-aa54-11ea-91ea-51d8f66bf04a.png)

**Comment by membranepotential** [comment]
probably fine now
