### ISSUE TITLE
Search performance

### ISSUE THREAD

**Issue by membranepotential** [membranepotential/ascstudymonitor#28]
Something is causing bad performance on search. Since we already have a search index it shouldnt be that slow. Please do your profiling magic to see if there is an easy fix ;-)

If its not easy, lets push it to 2.1.

**Comment by trueter** [comment]
With queries did you experience bad behavior with and do you agree that below 300ms should be acceptable?

**Comment by membranepotential** [comment]
In the end, setting debounce to a higher value (300) helped a lot
