### ISSUE TITLE
I know you guys love typographic quotation marks

### ISSUE THREAD

**Issue by membranepotential** [membranepotential/ascstudymonitor#32]
We have this article in the database:
https://www.sciencedirect.com/science/article/abs/pii/S0955395919301264

Maybe we can automatically replace quotation marks, as it seems like its the same on the Elsevier site?

**Comment by trueter** [comment]
What’s your suggested characters exactly? If the quotation marks should also be visible in meta tags and other consumers, a change on the backend / database level would make more sense. 👼
![image](https://user-images.githubusercontent.com/1976714/84549693-e9148080-ad08-11ea-8575-d12023e214d0.png)
