### ISSUE TITLE
Faceted search engine

### ISSUE THREAD

**Issue by trueter** [membranepotential/ascstudymonitor#7]
- Search by author doesn’t work at all. Eg. David Nutt => no results
 - Allow to set filters separately from search
 - Year filter deselection doesn’t work
 - Refactor URL construction
 - Deal with `null` years gracefully. So much grace.

**Comment by membranepotential** [comment]
Still open:
 - Search by author doesn’t work at all. Eg. David Nutt => no results

**Comment by trueter** [comment]
Please have another look.

**Comment by membranepotential** [comment]
Super done!
